main: tyze.bukkit.summerboss.App
name: SummerBoss
version: 1.1

commands:
    summerboss:
        description: create
        usage: /sboss create
        aliases: [sbs, sboss]

permissions:
    summerboss.create:
        default: op
    summerboss.reset:
        default: op
    summerboss.off:
        default: true